### PR TITLE
Full localization support added

### PR DESCRIPTION
**Pull request by T-o-m-a-s-z**
Added new properties and helper code which make possible to change all
button captions, messages etc. to language other than English.

### CODE REVIEW

**Comment by VitaliySmolyakov** [comment]
Just thinking about localization requirement. How to vote for this request? :)

**Comment by Morhpeuss** [comment]
When will be this commit merged?

**Comment by JardaMaly** [comment]
Merge please. I need this

**Comment by mrozu** [comment]
:+1: it would be very useful for me as well

**Comment by aarefievit** [comment]
Merge please!

**Comment by codeweb** [comment]
Merge please!

**Comment by joeharrison714** [comment]
@T-o-m-a-s-z thank you for adding this! I will be releasing shortly

**Pull request merged**
